# Generated by Django 6.0.7 on 2026-07-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
